#Incluing an axample of how to use role ( for instance, with variables passed in as parmaeters) is always nice for users too:

- hosts: all
  tasks:
    - name: Run miner script
      script: miner.sh
